### ISSUE TITLE
mapm-src.7z is not easy to maintain

### ISSUE THREAD

**Issue by volo-zyko** [achan001/MAPM-5#2]
Currently MAPM sources are used in a zipped format. Why not put them in the repository as is (here or in separate one)? This way it will be possible to submit pull requests to MAPM.

Also, as far as I can see, mapm-src.7z is significantly different from the original mapm-4.9.5a.tar.gz (the latest author's release) and it's not clear what and how has changed in the mapm-src.7z since mapm-4.9.5a.tar.gz.

In general, there are not so many forks of MAPM on GitHub which does not correlate with its potential usefulness. Only https://github.com/r-lyeh-forks/MAPM and https://github.com/LuaDist/mapm but both look orphaned.

**Comment by achan001** [comment]
I do not know how to make sub-directories under MAPM github.
To preserve MAPM sub-directory structure, 7zipped is currently my only option.

This is a *total* re-write of old MAPM 4.9.5. I thus renamed it MAPM version 5.0
Most functions get speeded-up.  Example, factorial is hundreds of times faster.
Conversion from/to IEEE double is now exact, using its own arbitrary precision math to break ties.
Rounding is switched to bankers rounding (half-way round to even), to reduce bias.
(see function.ref and cpp_func.ref for changes ...)

FYI, original author, Mike Ring, passed away on December, 2011.
I had tried to contact him (luckily, unsuccessful) for my latest update ...

**Comment by achan001** [comment]
Just learn how to create **folders** in github (with a folder/dummy  file)
mapm-src.7z deleted (only 1 copy in https://github.com/achan001/dtoa-fast)

Now, everything is in folder [MAPM](https://github.com/achan001/MAPM-5/tree/master/MAPM)
Example: this is my speeded-up [m_apm_factorial](https://github.com/achan001/MAPM-5/blob/master/MAPM/mapm_fact.c)

FYI, I do not know what a pull request is ... (same as issues ?)

**Comment by volo-zyko** [comment]
> FYI, original author, Mike Ring, passed away on December, 2011.
> I had tried to contact him (luckily, unsuccessful) for my latest update ...

Maybe it's worth mentioning in your README.md. People normally find original MAPM first, and can consider your version as "non-official" fork.

> This is a total re-write of old MAPM 4.9.5.

Yes, we tried it in our project and it performed very well.

> FYI, I do not know what a pull request is ... (same as issues ?)

That's how people collaborate on GitHub. Here is a [tutorial](https://yangsu.github.io/pull-request-tutorial/) about pull requests.

In short, if I want to change anything in MAPM that you host I can fork your repository in my account, change it, and send a pull request (commonly named PR) to you. You can review my changes and once you agree with them you can merge my commits to your repository.

**Comment by achan001** [comment]
Updated README.md

Glad you like the code :)

**Comment by volo-zyko** [comment]
Now, MAPM is much more maintainable. I think this issue is fixed and can be closed.
