### ISSUE TITLE
Compilation error in m_amp.h file

### ISSUE THREAD

**Issue by gsagoo** [achan001/MAPM-5#3]
Hello and thank you so much for keeping the MAPM library alive, I was very sad to hear about Mike Ring passing away. 
I am just reviving some old code, and noticed a slight issue with the header file, currently I am working around the issue by simply commenting out line 352 in the header file m_amp.h. (I am compiling on Linux Manjaro). 
Is there a better fix?
 
I am compiling with 
g++ pi_calc_mapm.cpp MAPM/libmapm.a -s -o piapproximate -lm

MAPM/m_apm.h:352:3: error: ‘MAPM::MAPM(int64_t)’ cannot be overloaded with ‘MAPM::MAPM(long int)’
  352 |   MAPM(int64_t l)     {create(); int64_t n = l<0 ? -l : l;
      |   ^~~~
MAPM/m_apm.h:349:3: note: previous declaration ‘MAPM::MAPM(long int)’
  349 |   MAPM(long l)        {create();m_apm_set_long(val(),l);}
      |   ^~~~

**Comment by achan001** [comment]
I removed the long type, which is too ambigous (4 bytes or 8 bytes)

**m_apm_set_long** is now renamed **m_apm_set_int** (assumed 4-bytes).

Note: this required updating other files that have m_apm_set_long.
Please download the full update, and report any errors.

**Comment by gsagoo** [comment]
That's great, I have downloaded and tested the new update and everything is working great. Thank you so much
